theme: jekyll-theme-minimal
title: Rebecca<br>Truong
logo: assets/img/turtlewater.png
description: Illustration by me.<br>OG Photo by <a href="https://unsplash.com/photos/M8xxVih_V_U">David Troeger.</a>
