theme: jekyll-theme-minimal
title: Rebecca Truong
logo: assets/img/turtlesketch2.png
description: Illustrated by me. Original photo by David Troeger | <a href="http://testing.test123.org/xx3/landing.gsp">Unsplash</a>
show_downloads: False
social-links-order:[github, medium, linkedin, email]
