theme: jekyll-theme-minimal
title: Rebecca Truong
logo: assets/img/turtlesketch2.png
description: Illustrated by me. Original photo by David Troeger | <a href="http://testing.test123.org/xx3/landing.gsp">Unsplash</a>

<div id="socialMedia">
{% if site.social-media.email %}
    <a href="mailto:{{ site.social-media.email }}" title="Email"><i class="fa fa-envelope-square"></i></a>
{% endif %}
{% if site.social-media.facebook %}
    <a href="https://www.facebook.com/{{ site.social-media.facebook }}" title="Facebook"><i class="fa fa-facebook-square"></i></a>
{% endif %}
{% if site.social-media.twitter %}
    <a href="https://www.twitter.com/{{ site.social-media.twitter }}" title="Twitter"><i class="fa fa-twitter-square"></i></a>
{% endif %}
