theme: jekyll-theme-minimal
title: Rebecca Truong
logo: assets/img/turtlewater.png
description: my website 
# Illustrated by me. Original photo by David Troeger | <a href="https://unsplash.com/photos/M8xxVih_V_U">Unsplash</a>
