theme: jekyll-theme-minimal
title: Rebecca Truong
logo: images/turtlesketch2.png
description: Illustrated by me. Original Photo by David Troeger | [Unsplash](https://unsplash.com/photos/M8xxVih_V_U) 
show_downloads: False
