theme: jekyll-theme-minimal
title: Rebecca Truong
logo: images/turtlesketch2.png
description: Illustrated by me. Original photo by David Troeger | <a href="http://testing.test123.org/xx3/landing.gsp">Unsplash</a>
show_downloads: False
